### ISSUE TITLE
New org mnemonics not showing up in search index

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#129]
Something funky is happening with org search...

* I created 2 orgs on dev:
    * `/orgs/SysOrg/`
    * `/orgs/SysOrg2/`
* These GET requests all work as expected: 
    * `/orgs/SysOrg/`
    * `/orgs/SysOrg2/`
    * `/orgs/`
    * `/orgs/?q=system` (Note that "system" is part of the org names) 
* However, zero results are returned on these: 
    * `GET /orgs/?q=sysorg`
    * `GET /orgs/?q=sysorg2`

It appears that the org mnemonics are not being indexed, but the full name and company of the orgs are being indexed.

**Comment by MisterNando** [comment]
Requires a partial Solr index update:

```
./manage.py update_index orgs.Organization
```

**Comment by paynejd** [comment]
Please advise how to run this on dev. I ran the command in the correct directory and received this error:

```
(ocl_api)deploy@dev:/opt/deploy/ocl_api/ocl$ ./manage.py update_index orgs.Organization
```
```
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/virtualenvs/ocl_api/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/opt/virtualenvs/ocl_api/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/virtualenvs/ocl_api/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/opt/virtualenvs/ocl_api/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/opt/virtualenvs/ocl_api/local/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/opt/virtualenvs/ocl_api/local/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._configure_logging()
  File "/opt/virtualenvs/ocl_api/local/lib/python2.7/site-packages/django/conf/__init__.py", line 84, in _configure_logging
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'logfile': [Errno 2] No such file or directory: '/opt/deploy/ocl_api/logs/ocl_api.log'
```

**Comment by MisterNando** [comment]
That "logs" directory was missing, so I recreated it.  Perhaps it was lost during the deploy?

**Comment by MisterNando** [comment]
Or perhaps the dev logging config should like more like the one in prod:

```
    ...
        'logfile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'when': 'midnight',
            'filename': '/var/log/ocl/ocl_api.log',
            'formatter': 'normal',
	    },
    ...
```
