### ISSUE TITLE
CSV download fails for concepts and mappings under collection version

### ISSUE THREAD

**Issue by AnjaliWadhwa** [OpenConceptLab/oclapi#261]
```
[06/Oct/2016 05:41:56] "GET /users/awadhwa1/collections/Anjalis-Collection/V1.2/mappings/?includeRetired=true&limit=10&verbose=true&page=1 HTTP/1.1" 200 12426
[2016/10/06 05:41:58] INFO    :  14.142.34.138 GET /users/awadhwa1/collections/Anjalis-Collection/V1.2/mappings/?csv=true&user=awadhwa1
Internal Server Error: /users/awadhwa1/collections/Anjalis-Collection/V1.2/mappings/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 327, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 324, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/mappings/views.py", line 197, in get
    return delegate_view(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 327, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 324, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/mappings/views.py", line 139, in get
    return self.list(request, *args, **kwargs)
  File "/code/oclapi/mixins.py", line 54, in list
    return self.get_csv(request)
  File "/code/oclapi/mixins.py", line 125, in get_csv
    url = write_csv_to_s3(data, is_member, **kwargs)
  File "/code/oclapi/utils.py", line 189, in write_csv_to_s3
    csv_file = csv_file_for(data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/djqscsv/djqscsv.py", line 49, in csv_file_for
    filename = _validate_and_clean_filename(filename)
  File "/usr/local/lib/python2.7/site-packages/djqscsv/djqscsv.py", line 181, in _validate_and_clean_filename
    raise ValidationError('the only accepted file extension is .csv')
ValidationError: [u'the only accepted file extension is .csv']
```

**Comment by mKadiyan** [comment]
This is Working fine
