### ISSUE TITLE
500 server error on POST and when reading NCoD concepts

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/oclapi#446]
Hi all,

I submitted a POST to create a new concept on production and it resulted in a 500 server error. Now, when I attempt to read concepts from the NCoD source I also receive a 500 server error: https://www.openconceptlab.org/orgs/EthiopiaNHDD/sources/NCoD/concepts/

Here's the POST and below is the error message.

```
POST https://api.openconceptlab.org/orgs/EthiopiaNHDD/sources/NCoD/concepts/  {"datatype": "None", "concept_class": "Diagnosis", "extras": {"ICD10-Block": "A00", "ICD10-Chapter": "Infectious & Parasitic"}, "names": [{"locale": "en", "locale_preferred": "True", "name_type": "Fully Specified", "name": "Cholera"}], "id": "1"}
```

```
Traceback (most recent call last):
  File "json_flex_import.py", line 317, in <module>
    ocl_importer.process()
  File "json_flex_import.py", line 135, in process
    self.process_object(obj_type, json_line_obj)
  File "json_flex_import.py", line 278, in process_object
    obj=obj, obj_not_allowed=obj_not_allowed)
  File "json_flex_import.py", line 309, in update_or_create
    request_post.raise_for_status()
  File "/Users/jonathanpayne/Virtualenvs/ocl_import/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://api.openconceptlab.org/orgs/EthiopiaNHDD/sources/NCoD/concepts/
```

![image](https://cloud.githubusercontent.com/assets/1189689/22309675/41bd1042-e31a-11e6-8b17-b2f366b361c3.png)

**Comment by emrah-b** [comment]
This is not an issue on environments beside production. Until the new version is deployed on production please make sure you have 
```json
{ "descriptions": [] }
```

in the json you post
