### ISSUE TITLE
concept retired flag not returned correctly for source

### ISSUE THREAD

**Issue by pkshiu** [OpenConceptLab/oclapi#60]
1. When getting concepts for a source, the retired flag is not returned when True. i.e. always set to false.

For example, these concepts are retired: 3, 5, 6, 9, 13, 14, 15, 16, 18, 19, 20, 23

http://api.dev.openconceptlab.com/v1/orgs/OMRS/sources/OMRS/concepts/?limit=25&page=2426

will return the 3/5/6 ones.

Whereas if you get the concept the retired flag is set correctly.

http://api.dev.openconceptlab.com/v1/orgs/OMRS/sources/OMRS/concepts/3/

2. Also -- potentially a second problem: for the sources/:source/concepts/ query, since "include_retired" should default to false, the 3/5/6 etc should not even be returned by default?

**Comment by MisterNando** [comment]
@paynejd, thought I fixed this one - are you still observing it?

**Comment by paynejd** [comment]
PK, please indicate if this is still happening.

--
Jonathan Payne, MS
615.579.5413
skype: jonathandavidpayne

**Comment by MisterNando** [comment]
@pkshiu , is this still happening?

**Comment by MisterNando** [comment]
I am unable to reproduce this right now:

http://api.dev.openconceptlab.com/v1/orgs/OMRS/sources/OMRS/concepts/?include_retired=true

yields 60637 results, whereas

http://api.dev.openconceptlab.com/v1/orgs/OMRS/sources/OMRS/concepts/

yields 59034 (for a difference of 1603).  As a sanity check, I ran this query in Mongo:

```
> db.concepts_concept.find({retired:true, parent_id:"545fc9d98a86f2738cac8b41"}).count()
```

which yields 1602.  Incidentally, this query:

```
> db.concepts_concept.find({retired:false, parent_id:"545fc9d98a86f2738cac8b41"}).count()
```

yields 59035, so that explains the "off by one"... but it's still a little curious that the numbers don't add up exactly.

**Comment by pkshiu** [comment]
The bug report text was not correct, sorry.

1) when searching across all concepts, retired concept (#3 ANEMIA) gets returned, without the flag.

http://api.dev.openconceptlab.com/v1/concepts/?limit=25&page=2426

2) Whether the count was wrong maybe related to (1).

**Comment by MisterNando** [comment]
@pkshiu , the problem is that there are 2 versions of this concept that think they're the "latest" version; one is retired and one is not; in the top-level search, you're seeing the one that is not.

There are 3 versions of this concept altogether: 5474bd768a86f2683cf31f7d, 548726bc8a86f253893b00ae, and 5488f2758a86f253893b06f3

They were created on 2014-11-25T12:33:42.561Z, 2014-12-09T11:43:40.534Z, and 2014-12-10T20:25:09.163Z, respectively.

The first one and the last one think they're the "latest" version, but I don't know why.  Can you shed any light as to how these 3 versions came into existence?  Is this case reproducible?

**Comment by paynejd** [comment]
Dev data is old and needs to be wiped. I recommend starting from scratch
and then trying to reproduce. Aaron, is it possible that the "re-import"
behavior isn't working correctly? That's my only guess as to how it could
have happened.

--
Jonathan Payne, MS
615.579.5413
skype: jonathandavidpayne

**Comment by pkshiu** [comment]
It is also possible that the initial "retiring" did not work properly when I was testing the retirement API.

@MisterNando if you can verify that correctly retired concepts are not returned nor counted then perhaps we can close the bug.

**Comment by MisterNando** [comment]
Yeah, Jon, I explored that possibility - and several others - but all the code paths seem to be updating the "is_latest_version" flag correctly.  That's why I'm trying to see if we can retrace our steps - perhaps with a smaller subset of data.

**Comment by MisterNando** [comment]
Demonstrated this with /orgs/HT04/sources/HT04S1/concepts/HT04-S1-C20/.

Was present in initial search:

http://api.dev.openconceptlab.com/v1/concepts/?q=HT04-S1-C20
(1 result)

Executed DELETE /orgs/HT04/sources/HT04S1/concepts/HT04-S1-C20/
(Returned 204)

Executed GET /orgs/HT04/sources/HT04S1/concepts/HT04-S1-C20/
(Attribute retired=true)

Searched again:

http://api.dev.openconceptlab.com/v1/concepts/?q=HT04-S1-C20
(0 results)

**Comment by MisterNando** [comment]
@pkshiu , please wipe the data on dev and reimport a smaller dataset (~1000).  Or remind me how, and I  will.  Thanks!

**Comment by MisterNando** [comment]
@paynejd - @pkshiu and I were able to isolate the problem: Solr is crapping out on the call to update the index.  Something along the lines of:

```
214678457 [qtp369285151-18] INFO  org.apache.solr.update.UpdateHandler  ? start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
214678463 [qtp369285151-18] INFO  org.apache.solr.update.processor.LogUpdateProcessor  ? [collection1] webapp=/solr path=/update/ params={commit=true} {add=[concepts.conceptversion.54e7eae650d61b1ed88ceb08]} 0 8
214678464 [qtp369285151-18] ERROR org.apache.solr.core.SolrCore  ? java.nio.file.NoSuchFileException: /opt/deploy/solr/collection1/data/index/_1y.fnm
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:334)
	at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:196)
	at org.apache.lucene.store.NRTCachingDirectory.openInput(NRTCachingDirectory.java:232)
	at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:113)
	at org.apache.lucene.codecs.lucene46.Lucene46FieldInfosReader.read(Lucene46FieldInfosReader.java:53)
	at org.apache.lucene.index.SegmentReader.readFieldInfos(SegmentReader.java:295)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:106)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:143)
	at org.apache.lucene.index.BufferedUpdatesStream.applyDeletesAndUpdates(BufferedUpdatesStream.java:282)
	at org.apache.lucene.index.IndexWriter.applyAllDeletesAndUpdates(IndexWriter.java:3322)
	at org.apache.lucene.index.IndexWriter.maybeApplyDeletes(IndexWriter.java:3313)
	at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3024)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3173)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3140)
	at org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:582)
	at org.apache.solr.update.processor.RunUpdateProcessor.processCommit(RunUpdateProcessorFactory.java:95)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processCommit(UpdateRequestProcessor.java:64)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalCommit(DistributedUpdateProcessor.java:1652)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processCommit(DistributedUpdateProcessor.java:1629)
	at org.apache.solr.update.processor.LogUpdateProcessor.processCommit(LogUpdateProcessorFactory.java:157)
	at org.apache.solr.handler.RequestHandlerUtils.handleCommit(RequestHandlerUtils.java:69)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:78)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:1962)
	at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:777)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:418)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:953)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1014)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

The odd thing is the inconsistency with which this is occurring.  In dev, it happened on retire, but not on update; in staging it happened on both retire and on update; in my local environment, it does not happen at all.

Can you do some research on this stack trace?  It looks like a core Solr bug.  I've already burnt a lot of cycles on this :-/

**Comment by MisterNando** [comment]
Blocked on #93
