### ISSUE TITLE
Solr update fails with java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by MisterNando** [OpenConceptLab/oclapi#93]
I believe this is the root cause for many of these issues (e.g. #60, #61, #62, etc.), so I'm factoring it out into its own ticket.  Here is the stack trace:

```
14678457 [qtp369285151-18] INFO  org.apache.solr.update.UpdateHandler  ? start commit{,optimize=false,openSearcher=true,waitSearcher=true,expungeDeletes=false,softCommit=false,prepareCommit=false}
214678463 [qtp369285151-18] INFO  org.apache.solr.update.processor.LogUpdateProcessor  ? [collection1] webapp=/solr path=/update/ params={commit=true} {add=[concepts.conceptversion.54e7eae650d61b1ed88ceb08]} 0 8
214678464 [qtp369285151-18] ERROR org.apache.solr.core.SolrCore  ? java.nio.file.NoSuchFileException: /opt/deploy/solr/collection1/data/index/_1y.fnm
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
    at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
    at java.nio.channels.FileChannel.open(FileChannel.java:287)
    at java.nio.channels.FileChannel.open(FileChannel.java:334)
    at org.apache.lucene.store.MMapDirectory.openInput(MMapDirectory.java:196)
    at org.apache.lucene.store.NRTCachingDirectory.openInput(NRTCachingDirectory.java:232)
    at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:113)
    at org.apache.lucene.codecs.lucene46.Lucene46FieldInfosReader.read(Lucene46FieldInfosReader.java:53)
    at org.apache.lucene.index.SegmentReader.readFieldInfos(SegmentReader.java:295)
    at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:106)
    at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:143)
    at org.apache.lucene.index.BufferedUpdatesStream.applyDeletesAndUpdates(BufferedUpdatesStream.java:282)
    at org.apache.lucene.index.IndexWriter.applyAllDeletesAndUpdates(IndexWriter.java:3322)
    at org.apache.lucene.index.IndexWriter.maybeApplyDeletes(IndexWriter.java:3313)
    at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3024)
    at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3173)
    at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3140)
    at org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:582)
    at org.apache.solr.update.processor.RunUpdateProcessor.processCommit(RunUpdateProcessorFactory.java:95)
    at org.apache.solr.update.processor.UpdateRequestProcessor.processCommit(UpdateRequestProcessor.java:64)
    at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalCommit(DistributedUpdateProcessor.java:1652)
    at org.apache.solr.update.processor.DistributedUpdateProcessor.processCommit(DistributedUpdateProcessor.java:1629)
    at org.apache.solr.update.processor.LogUpdateProcessor.processCommit(LogUpdateProcessorFactory.java:157)
    at org.apache.solr.handler.RequestHandlerUtils.handleCommit(RequestHandlerUtils.java:69)
    at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:78)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1962)
    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:777)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:418)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:368)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
    at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:953)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1014)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by MisterNando** [comment]
@paynejd , this is a big blocker.  There are a few different things we can try, but I can't afford to spend any more time here if we're going to finish all the enhancements.  We could try:

1. Uninstalling and reinstalling Solr.
2. Upgrade to the latest compatible version of Solr.
3. Tap a Solr resource for advice/workarounds.
4. Dig into the Solr source code.

Please advise.

**Comment by paynejd** [comment]
@MisterNando - You are the expert, so I need your recommendation as to the best method forward. #4 seems like a bad idea, esp. since we are not doing anything complicated with Solr. For #1, why don't you try this in production as it was just setup? That may save you a bit of time. Upgrading to Solr seems worth trying before #3.

**Comment by paynejd** [comment]
Could this also be some limitation from our VPS? If yes, the production VPS may address that.

**Comment by paynejd** [comment]
Could this also be some limitation from our VPS? If yes, the production VPS
may address that.

--
Jonathan Payne, MS
615.579.5413
skype: jonathandavidpayne

**Comment by MisterNando** [comment]
@pkshiu , can we repeat on prod the experiment we tried on dev and staging?  I should be online all day.

**Comment by MisterNando** [comment]
It's possible we were using a stale schema.xml, which may have been the root of this problem.  I ensured that the copy on dev is up to date, and then:
1. Stopped Jetty
2. Blew away the Solr index (rm -rf)
3. Restarted Jetty
4. Rebuilt the index
After completing these steps, I am no longer observing the update errors.  Let's keep an eye on this, though.

**Comment by pkshiu** [comment]
The schema.xml file is rebuilt each time according to the fabric script. (Remember I just copied the logic from the fabric script in the api side). i.e. it does this:

```
run("./manage.py build_solr_schema > /opt/deploy/solr/collection1/conf/schema.xml")
```

HOWEVER we had that solr backend mis-configuration, correct? So it probably wasn't even using the right schema file?

I want to make sure your fix is in the fabric script, otherwise it will just re-appear when we build new env.

**Comment by MisterNando** [comment]
Yup - that was the problem!  The configuration change was required for that command to build the correct index.

The only changes I would suggest for the fabric script would be to include the following options:
1. restart Solr
2. rebuild Solr index (although, as you mentioned, this can be run as a separate command).

**Comment by string-tanzeem** [comment]
The problem here is in accessing and creating new file in the data folder.
Just delete data file of the collection and restart the solr, hope everything would work fine.
